// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _en = {
  "onboarding_page1_title": "Book Appointments & Consultations",
  "onboarding_page1_subtitle": "You can request a Consultation from Doctors and Book Appointment with them 👨‍⚕️",
  "onboarding_page2_title": "Keep your Medical Records",
  "onboarding_page2_subtitle": "DomeCare allows you to keep your Medical Records safely at anytime, anywhere 🔐",
  "onboarding_page3_title": "Search for your Medication",
  "onboarding_page3_subtitle": "Get fully automated Medication leaflet and search for it in nearest pharmacies🚶‍♂️",
  "onboarding_getStarted": "Get Started",
  "login_welcome": "Welcome back to DomeCare 👋",
  "login_username": "Username",
  "login_password": "Password",
  "login_forgot_password": "Forgot password?",
  "login_log_in": "Log In",
  "login_create_account_cta": "Create Account",
  "login_new_to_app": "New to DomeCare?",
  "login_success": "Login successful",
  "login_failed": "Login failed",
  "login_username_required": "Username is required",
  "login_password_required": "Password is required",
  "login_password_no_spaces_allowed": "No spaces allowed",
  "login_password_at_least_8_characters": "At least 8 characters",
  "appointments_myAppointments": "My Appointments",
  "appointments_logout": "Logout",
  "appointments_clearTokens": "Clear both tokens",
  "appointments_testRefresh": "Test Refresh",
  "appointments_testSucceeded": "Test request succeeded",
  "appointments_testFailed": "Test request failed: {error}",
  "appointments_addNew": "Add New Appointment",
  "appointments_emptyState": "No appointments for this date.",
  "appointment_details_title": "Appointment Details",
  "appointment_contact_doctor_more_info": "Contact doctor for more information",
  "appointment_booking_title": "Book Appointment",
  "appointment_booking_subtitle": "Select a date and time for your appointment",
  "appointment_booking_date": "Date",
  "appointment_booking_time": "Time",
  "appointment_booking_submit": "Submit",
  "appointment_booking_cancel": "Cancel",
  "appointment_booking_confirm_title": "Confirm Appointment",
  "appointment_booking_confirm_subtitle": "Confirm the appointment and doctor",
  "appointment_booking_confirm_date": "Date",
  "appointment_booking_confirm_time": "Time",
  "appointment_booking_confirm_doctor": "Doctor",
  "appointment_booking_confirm_fee": "Fee",
  "appointment_booking_confirm_submit": "Confirm Appointment",
  "appointment_booking_confirm_next": "Next",
  "appointment_booking_confirm_cancel": "Cancel",
  "appointment_booking_confirm_success": "Appointment confirmed successfully",
  "appointment_booking_confirm_error": "Failed to confirm appointment",
  "doctors_bookAppointment": "Book Appointment",
  "doctors_searchHint": "Search for doctors",
  "booking_book_appointment": "Book Appointment",
  "booking_doctor_fee": "Doctor’s Fee",
  "details_title": "Details",
  "details_location": "Location",
  "details_phoneNumber": "Phone number",
  "details_telephone": "Telephone",
  "details_doctorFee": "Doctor Fee",
  "details_canceledReason": "Canceled Reason",
  "status_confirmed": "Confirmed",
  "status_pending": "Pending",
  "status_canceled": "Canceled",
  "status_rejected": "Rejected",
  "unknown": "Unknown"
};
static const Map<String,dynamic> _ar = {
  "onboarding_page1_title": "احجز المواعيد والاستشارات",
  "onboarding_page1_subtitle": "يمكنك طلب استشارة من الأطباء وحجز موعد معهم 👨‍⚕️",
  "onboarding_page2_title": "احتفظ بسجلاتك الطبية",
  "onboarding_page2_subtitle": "يتيح لك DomeCare الاحتفاظ بسجلاتك الطبية بأمان في أي وقت ومن أي مكان 🔐",
  "onboarding_page3_title": "ابحث عن أدويتك",
  "onboarding_page3_subtitle": "احصل على نشرة دوائية مؤتمتة بالكامل وابحث عنها في أقرب الصيدليات 🚶‍♂️",
  "onboarding_getStarted": "ابدأ الآن",
  "login_welcome": "مرحبًا بعودتك إلى DomeCare 👋",
  "login_username": "اسم المستخدم",
  "login_password": "كلمة المرور",
  "login_forgot_password": "هل نسيت كلمة المرور؟",
  "login_log_in": "تسجيل الدخول",
  "login_create_account_cta": "إنشاء حساب",
  "login_new_to_app": "جديد على DomeCare؟",
  "login_success": "تم تسجيل الدخول بنجاح",
  "login_failed": "فشل تسجيل الدخول",
  "login_username_required": "يجب أن يكون لديك اسم مستخدم",
  "login_phone_required": "يجب أن يكون لديك رقم هاتف",
  "login_password_required": "يجب أن يكون لديك كلمة مرور",
  "login_password_no_spaces_allowed": "لا يمكن أن يكون هناك مسافات",
  "login_password_at_least_8_characters": "يجب أن يكون لديك 8 أحرف على الأقل",
  "appointments_myAppointments": "مواعيدي",
  "appointments_logout": "تسجيل الخروج",
  "appointments_clearTokens": "مسح الرموز",
  "appointments_testRefresh": "اختبار التحديث",
  "appointments_testSucceeded": "نجح طلب الاختبار",
  "appointments_testFailed": "فشل طلب الاختبار: {error}",
  "appointments_addNew": "إضافة موعد جديد",
  "appointments_emptyState": "لا توجد مواعيد في هذا التاريخ.",
  "appointment_details_title": "تفاصيل الموعد",
  "appointment_contact_doctor_more_info": "تواصل مع الطبيب للحصول على مزيد من المعلومات",
  "appointment_booking_title": "حجز موعد",
  "appointment_booking_subtitle": "اختر تاريخ ووقت الموعد",
  "appointment_booking_date": "التاريخ",
  "appointment_booking_time": "الوقت",
  "appointment_booking_submit": "إرسال",
  "appointment_booking_cancel": "إلغاء",
  "appointment_booking_confirm_title": "تأكيد الحجز",
  "appointment_booking_confirm_subtitle": "تأكد من الموعد والطبيب",
  "appointment_booking_confirm_date": "التاريخ",
  "appointment_booking_confirm_time": "الوقت",
  "appointment_booking_confirm_doctor": "الطبيب",
  "appointment_booking_confirm_fee": "الرسوم",
  "appointment_booking_confirm_submit": "تأكيد الحجز",
  "appointment_booking_confirm_next": "التالي",
  "appointment_booking_confirm_cancel": "إلغاء",
  "appointment_booking_confirm_success": "تم تأكيد الحجز بنجاح",
  "appointment_booking_confirm_error": "فشل تأكيد الحجز",
  "doctors_bookAppointment": "حجز موعد",
  "doctors_searchHint": "ابحث عن طبيب",
  "booking_book_appointment": "حجز موعد",
  "booking_doctor_fee": "رسوم الطبيب",
  "details_title": "التفاصيل",
  "details_location": "الموقع",
  "details_phoneNumber": "رقم الهاتف",
  "details_telephone": "هاتف ثابت",
  "details_doctorFee": "أتعاب الطبيب",
  "details_canceledReason": "سبب الإلغاء",
  "status_confirmed": "مؤكد",
  "status_pending": "قيد الانتظار",
  "status_canceled": "ملغى",
  "status_rejected": "مرفوض",
  "unknown": "غير معروف"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": _en, "ar": _ar};
}
